// ⚙️ TanStack Query Keys
export enum QueryKeys {
  authUser = 'authUser',
  patientAppointments = 'patientAppointments',
  patientWaitlists = 'patientWaitlists',
  allWaitlists = 'allWaitlists',
  patientResults = 'patientResults',
  patientQR = 'patientQR',
  patientReceipt = 'patientReceipt',

  donorCampaigns = 'donorCampaigns',
  donorCampaign = 'donorCampaign',
  donorReceipts = 'donorReceipts',
  donorImpact = 'donorImpact',
  verifyPayment = 'verifyPayment',

  centerAppointments = 'centerAppointments',
  centerResults = 'centerResults',
  centerStaff = 'centerStaff',
  centerReceipts = 'centerReceipts',
  centers = 'centers',
  centerById = 'centerById',

  adminUsers = 'adminUsers',
  adminCenters = 'adminCenters',
  adminCampaigns = 'adminCampaigns',
  adminAppointments = 'adminAppointments',
  adminTransactions = 'adminTransactions',
  adminWaitlist = 'adminWaitlist',
  adminStoreProducts = 'adminStoreProducts',
  adminAnalytics = 'adminAnalytics',
  adminStore = 'adminStore',
  adminRoles = 'adminRoles',
  checkProfiles = 'checkProfiles',

  // Screening type queries
  screeningTypes = 'screeningTypes',
  screeningTypesAll = 'screeningTypesAll',
  screeningTypeCategories = 'screeningTypeCategories',
  screeningTypesCategory = 'screeningTypesCategory',
  screeningType = 'screeningType',
  screeningTypeByName = 'screeningTypeByName',
  centerAppointmentById = 'centerAppointmentById',
}

export enum MutationKeys {
  registerPatient = 'registerPatient',
  registerDonor = 'registerDonor',
  registerCenter = 'registerCenter',
  forgotPassword = 'forgotPassword',
  resetPassword = 'resetPassword',
  verifyEmail = 'verifyEmail',
  loginUser = 'loginUser',
  authUser = 'authUser',
  logoutUser = 'logoutUser',
  joinWaitlist = 'joinWaitlist',
  bookAppointment = 'bookAppointment',
  uploadResult = 'uploadResult',
  verifyPatient = 'verifyPatient',
  createCampaign = 'createCampaign',
  fundCampaign = 'fundCampaign',
  updateCampaign = 'updateCampaign',
  deleteCampaign = 'deleteCampaign',
  approveCenter = 'approveCenter',
  updateCampaignStatus = 'updateCampaignStatus',
  resendReceipt = 'resendReceipt',
  donateAnonymous = 'donateAnonymous',
  inviteStaff = 'inviteStaff',
  createCenterStaffPassword = 'createCenterStaffPassword',
  resendVerification = 'resendVerification',
  selectCenter = 'selectCenter',
  // Notification mutations
  markNotificationRead = 'markNotificationRead',
  createNotification = 'createNotification',
  centerStaffForgotPassword = 'centerStaffForgotPassword',
  centerStaffResetPassword = 'centerStaffResetPassword',
  centerStaffLogin = 'centerStaffLogin',
  // Appointment mutations
  cancelCenterAppointment = 'cancelCenterAppointment',
  verifyCheckInCode = 'verifyCheckInCode',
  // Result file mutations
  deleteResultFile = 'deleteResultFile',
  restoreResultFile = 'restoreResultFile',
  completeAppointment = 'completeAppointment',
  // Admin mutations
  adminLogin = 'adminLogin',
  adminForgotPassword = 'adminForgotPassword',
  adminResetPassword = 'adminResetPassword',
  createAdmin = 'createAdmin',
  updateCenterStatus = 'updateCenterStatus',
  updateAdminCampaignStatus = 'updateAdminCampaignStatus',
  createStoreProduct = 'createStoreProduct',
  updateStoreProduct = 'updateStoreProduct',
}

export const ACCESS_TOKEN_KEY = 'accessToken'
